server:
  port: 8082

spring:
  application:
    name: post-service
  datasource:
    master:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
    slave:
      jdbc-url: jdbc:postgresql://localhost:5433/postgres
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
minio:
  bucket: postimage
  url: http://localhost:9000
  access-key: user
  secret-key: Damir2005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
topic:
  like-post: "like-events"
  comment-post: "comment-events"
  created-post: "post-events"
resilience4j:
  circuitbreaker:
    instances:
      categoryService:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 5
image:
  url: "http://localhost:8081/images/"
